# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Akshay Ojha
tagline:          The lazy coder
url:              http://akshayojha.github.io
paginate:         1
baseurl:          /
author:
  name:           Akshay Ojha
  url:            https://twitter.com/callhimakshay
  email:          ojha@ccs.neu.edu

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/akshayojha
